BEGIN TRANSACTION;
INSERT INTO "User" VALUES (1,'doc','doc@hospital.com',2,1,NULL,NULL);
INSERT INTO "User" VALUES (2,'researcher','res@uni.se',3,2,NULL,NULL);
INSERT INTO "User" VALUES (3,'patient1','x@gmail.com',1,1,59.6567,16.6709);
INSERT INTO "User" VALUES (4,'patient2','y@happyemail.com',1,1,57.3365,12.5164);
INSERT INTO "Organization" VALUES (1,'Hospital');
INSERT INTO "Organization" VALUES (2,'LNU University');
INSERT INTO "Role" VALUES (1,'patient','1');
INSERT INTO "Role" VALUES (2,'physician','2');
INSERT INTO "Role" VALUES (3,'researcher','3');
INSERT INTO "Role" VALUES (4,'junior researcher','3');
INSERT INTO "Note" VALUES (1,1,'Well this is interesting.',2);
INSERT INTO "Note" VALUES (2,1,'This seams a bit weird.',1);
INSERT INTO "Test_Session" VALUES (1,1,1,'data1');
INSERT INTO "Test_Session" VALUES (2,2,1,'data2');
INSERT INTO "Test_Session" VALUES (3,1,2,'data3');
INSERT INTO "Test_Session" VALUES (4,2,2,'data4');
INSERT INTO "Test_Session" VALUES (5,1,3,'data5');
INSERT INTO "Test_Session" VALUES (6,2,3,'data6');
INSERT INTO "Test" VALUES (1,'2009-12-01 18:00:00',1);
INSERT INTO "Test" VALUES (2,'2009-12-02 18:00:00',1);
INSERT INTO "Test" VALUES (3,'2009-12-02 18:00:00',2);
INSERT INTO "Therapy" VALUES (1,3,1,1);
INSERT INTO "Therapy" VALUES (2,4,1,1);
INSERT INTO "Therapy_List" VALUES (1,'Therapy trials with Medicine 1',1,'400 ml');
INSERT INTO "Medicine" VALUES (1,'Medicine 1');
INSERT INTO "Medicine" VALUES (2,'Medicine 2');
COMMIT;
